services:
  blender-mcp:
    container_name: blender-mcp
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    image: mcp/blender-mcp
    read_only: false
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
      - seccomp=unconfined
    tmpfs:
      - /tmp
      - /root/.cache
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - isolated

networks:
  isolated:
    driver: bridge
    internal: false